# Generated by Django 5.2.15 on 2026-06-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField()),
                ('prompt', models.TextField()),
                ('number_of_images', models.IntegerField(default=1)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('max_retries_number', models.IntegerField(default=3)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('cost_usd', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['idempotency_key'], name='jobs_job_idempot_ddf6e2_idx'), models.Index(fields=['user_id', 'status'], name='jobs_job_user_id_ec4047_idx')],
            },
        ),
    ]
