# Generated by Django 5.2.15 on 2026-06-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_celery_task_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_idempot_ddf6e2_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='cost_usd',
        ),
        migrations.RemoveField(
            model_name='job',
            name='image_url',
        ),
        migrations.AddField(
            model_name='job',
            name='result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
