# Generated by Django 5.2.15 on 2026-06-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_job_jobs_job_idempot_ddf6e2_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='error_message',
        ),
        migrations.AddField(
            model_name='job',
            name='error_messages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
